#!/bin/bash
export TUTO_HOME=~/'tutorial de git e github'
TUTO=github.com/paulojeronimo/tutorial-git-github

rm -rf "$TUTO_HOME"

mkdir -p "$TUTO_HOME"
cat > "$TUTO_HOME"/ambiente <<'EOF'
export SEU_NOME='Aluno do PJ'
export SEU_USUARIO=alunodopj
export SEU_TWITTER=@alunodopj
EOF

source "$TUTO_HOME"/ambiente

d="$TUTO_HOME"/github.com/paulojeronimo
mkdir -p "$d" && cd "$d"
git clone https://$TUTO.git

d="$TUTO_HOME"/github.com/$SEU_USUARIO
mkdir -p "$d" && cd "$d"
cp -r "$TUTO_HOME"/$TUTO/slides-no-github/* .
cp -r "$TUTO_HOME"/$TUTO/{atributos.conf,build} .

./ajustar-usuario.sh
